services:
  db:
    image: postgres:15-alpine
    container_name: vetclinic_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - vetclinic_network

  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: vetclinic_web
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    networks:
      - vetclinic_network

  nginx:
    build:
      context: ./docker/nginx
    container_name: vetclinic_nginx
    volumes:
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "127.0.0.1:8090:80"
    depends_on:
      - web
    restart: always
    networks:
      - vetclinic_network

  redis:
    image: redis:7-alpine
    container_name: vetclinic_redis
    restart: always
    networks:
      - vetclinic_network

  celery:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: vetclinic_celery
    command: celery -A clinic worker -l info
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    depends_on:
      - db
      - redis
    restart: always
    networks:
      - vetclinic_network

volumes:
  postgres_data:
  static_volume:
  media_volume:


networks:
  vetclinic_network:
    driver: bridge
